export { AppComponent } from '../app.component';
export { LoginComponent } from '../auth/login/login.component';
export { RegisterComponent } from '../auth/register/register.component';
export { DashboardComponent } from '../management/dashboard/dashboard.component';
export { AuthComponent } from '../auth/auth.component';
export { ManagementComponent } from '../management/management.component';
export { ArticleComponent } from '../management/article/article.component';
export { LogoutComponent } from '../auth/logout/logout.component';
export { ArticleTrashComponent } from '../management/article/article-trash/article-trash.component';
export { AlbumsComponent } from '../management/albums/albums.component'
export { ImageEditComponent } from '../management/albums/image-edit/image-edit.component';
export { AdminPanelComponent } from '../management/admin/admin-panel/admin-panel.component';
export { CategoriesComponent } from '../management/admin/categories/categories.component';
export { MenusComponent } from '../management/admin/menus/menus.component';
export { LanguagesComponent } from '../management/admin/languages/languages.component';
export { ProfileComponent } from '../management/profile/profile.component';
export { PageNotFoundComponent }  from '../system/page-not-found/page-not-found.component'
export { RedirectComponent }  from '../system/redirect/redirect.component'
